version: '3'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 5
    environment:
      LANG: C.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pk-portal
    volumes:
      - pgsql_data:/var/lib/postgresql/data
  pkportal-be:
    image: pkportal-be:latest
    ports:
      - "5000:5000"
    volumes:
      - "pkportal-be:/app"
    depends_on:
      - postgres

volumes:
  pgsql_data:
    driver: local
  pkportal-be:
    driver: local