CREATE TYPE user_role AS ENUM ('admin', 'user');
CREATE TYPE user_gender AS ENUM ('male', 'female');
CREATE TYPE test_date_pub_status AS ENUM ('shown', 'hidden');

CREATE TABLE IF NOT EXISTS public.users
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    email               text UNIQUE              NOT NULL,
    hash_password       text                     NOT NULL,
    fio                 text                     NOT NULL,
    date_of_birth       date                     NOT NULL,
    gender              user_gender              NOT NULL,
    phone_number        text                     NOT NULL,
    parent_phone_number text                     NOT NULL,
    current_school      text,
    education_year      smallint                 NOT NULL,
    role                user_role DEFAULT 'user' NOT NULL
);

CREATE TABLE IF NOT EXISTS public.test_dates
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    date_time      timestamp with time zone NOT NULL,
    location       text                     NOT NULL,
    max_persons    integer                  NOT NULL,
    education_year smallint                 NOT NULL,
    pub_status     test_date_pub_status     NOT NULL DEFAULT 'shown'
);

CREATE TABLE IF NOT EXISTS public.user_test_dates
(
    user_id        bigint REFERENCES public.users (id)      NOT NULL,
    test_date_id   bigint REFERENCES public.test_dates (id) NOT NULL,
    education_year smallint                                 NOT NULL,
    is_attended    boolean                                  NOT NULL DEFAULT false,
    PRIMARY KEY (user_id, education_year)
);

CREATE TABLE IF NOT EXISTS public.profiles
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    name           text     NOT NULL,
    education_year smallint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.subjects
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.profile_subjects
(
    profile_id bigint REFERENCES public.profiles (id) NOT NULL,
    subject_id bigint REFERENCES public.subjects (id) NOT NULL,
    PRIMARY KEY (profile_id, subject_id)
);

CREATE TABLE IF NOT EXISTS public.user_profiles
(
    user_id             bigint REFERENCES public.users (id) NOT NULL,
    user_education_year smallint                            NOT NULL,
    first_profile_id    bigint REFERENCES public.profiles (id),
    second_profile_id   bigint REFERENCES public.profiles (id),
    PRIMARY KEY (user_id, user_education_year)
);

CREATE TABLE IF NOT EXISTS public.user_profile_subjects
(
    user_id                   bigint REFERENCES public.users (id) NOT NULL,
    user_education_year       smallint                            NOT NULL,
    first_profile_subject_id  bigint REFERENCES public.subjects (id),
    second_profile_subject_id bigint REFERENCES public.subjects (id),
    PRIMARY KEY (user_id, user_education_year)
);

CREATE TABLE IF NOT EXISTS public.foreign_languages
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_foreign_languages
(
    user_id             bigint REFERENCES public.users (id) NOT NULL,
    user_education_year smallint                            NOT NULL,
    foreign_language_id bigint REFERENCES public.foreign_languages (id),
    PRIMARY KEY (user_id, user_education_year)
);