// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package tpportal

var TableNames = struct {
	ForeignLanguages     string
	ProfileSubjects      string
	Profiles             string
	Subjects             string
	TestDates            string
	UserForeignLanguages string
	UserProfileSubjects  string
	UserProfiles         string
	UserTestDates        string
	Users                string
}{
	ForeignLanguages:     "foreign_languages",
	ProfileSubjects:      "profile_subjects",
	Profiles:             "profiles",
	Subjects:             "subjects",
	TestDates:            "test_dates",
	UserForeignLanguages: "user_foreign_languages",
	UserProfileSubjects:  "user_profile_subjects",
	UserProfiles:         "user_profiles",
	UserTestDates:        "user_test_dates",
	Users:                "users",
}
