// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package tpportal

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// CommonTestDateAddress is an object representing the database table.
type CommonTestDateAddress struct {
	ID   int64  `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`

	R *commonTestDateAddressR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L commonTestDateAddressL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CommonTestDateAddressColumns = struct {
	ID   string
	Name string
}{
	ID:   "id",
	Name: "name",
}

var CommonTestDateAddressTableColumns = struct {
	ID   string
	Name string
}{
	ID:   "common_test_date_addresses.id",
	Name: "common_test_date_addresses.name",
}

// Generated where

var CommonTestDateAddressWhere = struct {
	ID   whereHelperint64
	Name whereHelperstring
}{
	ID:   whereHelperint64{field: "\"common_test_date_addresses\".\"id\""},
	Name: whereHelperstring{field: "\"common_test_date_addresses\".\"name\""},
}

// CommonTestDateAddressRels is where relationship names are stored.
var CommonTestDateAddressRels = struct {
}{}

// commonTestDateAddressR is where relationships are stored.
type commonTestDateAddressR struct {
}

// NewStruct creates a new relationship struct
func (*commonTestDateAddressR) NewStruct() *commonTestDateAddressR {
	return &commonTestDateAddressR{}
}

// commonTestDateAddressL is where Load methods for each relationship are stored.
type commonTestDateAddressL struct{}

var (
	commonTestDateAddressAllColumns            = []string{"id", "name"}
	commonTestDateAddressColumnsWithoutDefault = []string{"name"}
	commonTestDateAddressColumnsWithDefault    = []string{"id"}
	commonTestDateAddressPrimaryKeyColumns     = []string{"id"}
	commonTestDateAddressGeneratedColumns      = []string{}
)

type (
	// CommonTestDateAddressSlice is an alias for a slice of pointers to CommonTestDateAddress.
	// This should almost always be used instead of []CommonTestDateAddress.
	CommonTestDateAddressSlice []*CommonTestDateAddress
	// CommonTestDateAddressHook is the signature for custom CommonTestDateAddress hook methods
	CommonTestDateAddressHook func(context.Context, boil.ContextExecutor, *CommonTestDateAddress) error

	commonTestDateAddressQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	commonTestDateAddressType                 = reflect.TypeOf(&CommonTestDateAddress{})
	commonTestDateAddressMapping              = queries.MakeStructMapping(commonTestDateAddressType)
	commonTestDateAddressPrimaryKeyMapping, _ = queries.BindMapping(commonTestDateAddressType, commonTestDateAddressMapping, commonTestDateAddressPrimaryKeyColumns)
	commonTestDateAddressInsertCacheMut       sync.RWMutex
	commonTestDateAddressInsertCache          = make(map[string]insertCache)
	commonTestDateAddressUpdateCacheMut       sync.RWMutex
	commonTestDateAddressUpdateCache          = make(map[string]updateCache)
	commonTestDateAddressUpsertCacheMut       sync.RWMutex
	commonTestDateAddressUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var commonTestDateAddressAfterSelectHooks []CommonTestDateAddressHook

var commonTestDateAddressBeforeInsertHooks []CommonTestDateAddressHook
var commonTestDateAddressAfterInsertHooks []CommonTestDateAddressHook

var commonTestDateAddressBeforeUpdateHooks []CommonTestDateAddressHook
var commonTestDateAddressAfterUpdateHooks []CommonTestDateAddressHook

var commonTestDateAddressBeforeDeleteHooks []CommonTestDateAddressHook
var commonTestDateAddressAfterDeleteHooks []CommonTestDateAddressHook

var commonTestDateAddressBeforeUpsertHooks []CommonTestDateAddressHook
var commonTestDateAddressAfterUpsertHooks []CommonTestDateAddressHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CommonTestDateAddress) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commonTestDateAddressAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CommonTestDateAddress) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commonTestDateAddressBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CommonTestDateAddress) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commonTestDateAddressAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CommonTestDateAddress) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commonTestDateAddressBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CommonTestDateAddress) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commonTestDateAddressAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CommonTestDateAddress) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commonTestDateAddressBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CommonTestDateAddress) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commonTestDateAddressAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CommonTestDateAddress) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commonTestDateAddressBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CommonTestDateAddress) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commonTestDateAddressAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCommonTestDateAddressHook registers your hook function for all future operations.
func AddCommonTestDateAddressHook(hookPoint boil.HookPoint, commonTestDateAddressHook CommonTestDateAddressHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		commonTestDateAddressAfterSelectHooks = append(commonTestDateAddressAfterSelectHooks, commonTestDateAddressHook)
	case boil.BeforeInsertHook:
		commonTestDateAddressBeforeInsertHooks = append(commonTestDateAddressBeforeInsertHooks, commonTestDateAddressHook)
	case boil.AfterInsertHook:
		commonTestDateAddressAfterInsertHooks = append(commonTestDateAddressAfterInsertHooks, commonTestDateAddressHook)
	case boil.BeforeUpdateHook:
		commonTestDateAddressBeforeUpdateHooks = append(commonTestDateAddressBeforeUpdateHooks, commonTestDateAddressHook)
	case boil.AfterUpdateHook:
		commonTestDateAddressAfterUpdateHooks = append(commonTestDateAddressAfterUpdateHooks, commonTestDateAddressHook)
	case boil.BeforeDeleteHook:
		commonTestDateAddressBeforeDeleteHooks = append(commonTestDateAddressBeforeDeleteHooks, commonTestDateAddressHook)
	case boil.AfterDeleteHook:
		commonTestDateAddressAfterDeleteHooks = append(commonTestDateAddressAfterDeleteHooks, commonTestDateAddressHook)
	case boil.BeforeUpsertHook:
		commonTestDateAddressBeforeUpsertHooks = append(commonTestDateAddressBeforeUpsertHooks, commonTestDateAddressHook)
	case boil.AfterUpsertHook:
		commonTestDateAddressAfterUpsertHooks = append(commonTestDateAddressAfterUpsertHooks, commonTestDateAddressHook)
	}
}

// One returns a single commonTestDateAddress record from the query.
func (q commonTestDateAddressQuery) One(ctx context.Context, exec boil.ContextExecutor) (*CommonTestDateAddress, error) {
	o := &CommonTestDateAddress{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tpportal: failed to execute a one query for common_test_date_addresses")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all CommonTestDateAddress records from the query.
func (q commonTestDateAddressQuery) All(ctx context.Context, exec boil.ContextExecutor) (CommonTestDateAddressSlice, error) {
	var o []*CommonTestDateAddress

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "tpportal: failed to assign all query results to CommonTestDateAddress slice")
	}

	if len(commonTestDateAddressAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all CommonTestDateAddress records in the query.
func (q commonTestDateAddressQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: failed to count common_test_date_addresses rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q commonTestDateAddressQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "tpportal: failed to check if common_test_date_addresses exists")
	}

	return count > 0, nil
}

// CommonTestDateAddresses retrieves all the records using an executor.
func CommonTestDateAddresses(mods ...qm.QueryMod) commonTestDateAddressQuery {
	mods = append(mods, qm.From("\"common_test_date_addresses\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"common_test_date_addresses\".*"})
	}

	return commonTestDateAddressQuery{q}
}

// FindCommonTestDateAddress retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCommonTestDateAddress(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*CommonTestDateAddress, error) {
	commonTestDateAddressObj := &CommonTestDateAddress{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"common_test_date_addresses\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, commonTestDateAddressObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tpportal: unable to select from common_test_date_addresses")
	}

	if err = commonTestDateAddressObj.doAfterSelectHooks(ctx, exec); err != nil {
		return commonTestDateAddressObj, err
	}

	return commonTestDateAddressObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CommonTestDateAddress) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("tpportal: no common_test_date_addresses provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(commonTestDateAddressColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	commonTestDateAddressInsertCacheMut.RLock()
	cache, cached := commonTestDateAddressInsertCache[key]
	commonTestDateAddressInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			commonTestDateAddressAllColumns,
			commonTestDateAddressColumnsWithDefault,
			commonTestDateAddressColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(commonTestDateAddressType, commonTestDateAddressMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(commonTestDateAddressType, commonTestDateAddressMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"common_test_date_addresses\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"common_test_date_addresses\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "tpportal: unable to insert into common_test_date_addresses")
	}

	if !cached {
		commonTestDateAddressInsertCacheMut.Lock()
		commonTestDateAddressInsertCache[key] = cache
		commonTestDateAddressInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the CommonTestDateAddress.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CommonTestDateAddress) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	commonTestDateAddressUpdateCacheMut.RLock()
	cache, cached := commonTestDateAddressUpdateCache[key]
	commonTestDateAddressUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			commonTestDateAddressAllColumns,
			commonTestDateAddressPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("tpportal: unable to update common_test_date_addresses, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"common_test_date_addresses\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, commonTestDateAddressPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(commonTestDateAddressType, commonTestDateAddressMapping, append(wl, commonTestDateAddressPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to update common_test_date_addresses row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: failed to get rows affected by update for common_test_date_addresses")
	}

	if !cached {
		commonTestDateAddressUpdateCacheMut.Lock()
		commonTestDateAddressUpdateCache[key] = cache
		commonTestDateAddressUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q commonTestDateAddressQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to update all for common_test_date_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to retrieve rows affected for common_test_date_addresses")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CommonTestDateAddressSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("tpportal: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commonTestDateAddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"common_test_date_addresses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, commonTestDateAddressPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to update all in commonTestDateAddress slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to retrieve rows affected all in update all commonTestDateAddress")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CommonTestDateAddress) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("tpportal: no common_test_date_addresses provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(commonTestDateAddressColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	commonTestDateAddressUpsertCacheMut.RLock()
	cache, cached := commonTestDateAddressUpsertCache[key]
	commonTestDateAddressUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			commonTestDateAddressAllColumns,
			commonTestDateAddressColumnsWithDefault,
			commonTestDateAddressColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			commonTestDateAddressAllColumns,
			commonTestDateAddressPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("tpportal: unable to upsert common_test_date_addresses, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(commonTestDateAddressPrimaryKeyColumns))
			copy(conflict, commonTestDateAddressPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"common_test_date_addresses\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(commonTestDateAddressType, commonTestDateAddressMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(commonTestDateAddressType, commonTestDateAddressMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "tpportal: unable to upsert common_test_date_addresses")
	}

	if !cached {
		commonTestDateAddressUpsertCacheMut.Lock()
		commonTestDateAddressUpsertCache[key] = cache
		commonTestDateAddressUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single CommonTestDateAddress record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CommonTestDateAddress) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("tpportal: no CommonTestDateAddress provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), commonTestDateAddressPrimaryKeyMapping)
	sql := "DELETE FROM \"common_test_date_addresses\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to delete from common_test_date_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: failed to get rows affected by delete for common_test_date_addresses")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q commonTestDateAddressQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("tpportal: no commonTestDateAddressQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to delete all from common_test_date_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: failed to get rows affected by deleteall for common_test_date_addresses")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CommonTestDateAddressSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(commonTestDateAddressBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commonTestDateAddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"common_test_date_addresses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, commonTestDateAddressPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to delete all from commonTestDateAddress slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: failed to get rows affected by deleteall for common_test_date_addresses")
	}

	if len(commonTestDateAddressAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CommonTestDateAddress) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCommonTestDateAddress(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CommonTestDateAddressSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CommonTestDateAddressSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commonTestDateAddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"common_test_date_addresses\".* FROM \"common_test_date_addresses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, commonTestDateAddressPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "tpportal: unable to reload all in CommonTestDateAddressSlice")
	}

	*o = slice

	return nil
}

// CommonTestDateAddressExists checks if the CommonTestDateAddress row exists.
func CommonTestDateAddressExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"common_test_date_addresses\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "tpportal: unable to check if common_test_date_addresses exists")
	}

	return exists, nil
}

// Exists checks if the CommonTestDateAddress row exists.
func (o *CommonTestDateAddress) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CommonTestDateAddressExists(ctx, exec, o.ID)
}
